import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("boutique", "routes/shop.tsx"),
  route("boutique/:slug", "routes/product.tsx"),
  route("produit/:slug", "routes/legacy-redirect.ts", { id: "legacy-product-fr" }),
  route("product/:slug", "routes/legacy-redirect.ts", { id: "legacy-product-root" }),
  route("archives", "routes/archives.tsx"),
  route("conseils", "routes/advice.tsx"),
  route("conseils/:slug", "routes/advice-detail.tsx"),
  route("a-propos", "routes/about.tsx"),
  route("professionnel", "routes/professional.tsx"),
  route("faq", "routes/faq.tsx"),
  route("contact", "routes/contact.tsx"),
  route("cgv", "routes/legal.tsx", { id: "terms-fr" }),
  route("mentions-legales", "routes/legal.tsx", { id: "legal-fr" }),
  route("politique-de-confidentialite", "routes/legal.tsx", { id: "privacy-fr" }),
  route("panier", "routes/cart.tsx"),
  route("commande", "routes/checkout.tsx"),
  route("commande/confirmation", "routes/confirmation.tsx"),
  route("mon-compte", "routes/account.tsx"),
  route("auth/confirm", "routes/auth-confirm.ts"),
  route("admin", "routes/admin.tsx"),
  route("admin/produits/:id", "routes/admin-product.tsx"),
  route("admin/commandes", "routes/admin-orders.tsx"),
  route("admin/commandes.csv", "routes/admin-orders-csv.ts"),
  route("admin/expedition", "routes/admin-shipping.tsx"),
  route("admin/professionnels", "routes/admin-professionals.tsx"),
  route("admin/contenus", "routes/admin-content.tsx"),
  route("admin/editorial", "routes/admin-editorial.tsx"),
  route("en", "routes/home.tsx", { id: "home-en" }),
  route("en/shop", "routes/shop.tsx", { id: "shop-en" }),
  route("en/shop/:slug", "routes/product.tsx", { id: "product-en" }),
  route("en/product/:slug", "routes/legacy-redirect.ts", { id: "legacy-product-en" }),
  route("en/archives", "routes/archives.tsx", { id: "archives-en" }),
  route("en/tips", "routes/advice.tsx", { id: "advice-en" }),
  route("en/tips/:slug", "routes/advice-detail.tsx", { id: "advice-detail-en" }),
  route("en/about-us", "routes/about.tsx", { id: "about-en" }),
  route("en/professional", "routes/professional.tsx", { id: "professional-en" }),
  route("en/faq", "routes/faq.tsx", { id: "faq-en" }),
  route("en/contact", "routes/contact.tsx", { id: "contact-en" }),
  route("en/general-terms-and-conditions-of-sale", "routes/legal.tsx", { id: "terms-en" }),
  route("en/legal-notice", "routes/legal.tsx", { id: "legal-en" }),
  route("en/privacy-policy", "routes/legal.tsx", { id: "privacy-en" }),
  route("en/cart", "routes/cart.tsx", { id: "cart-en" }),
  route("en/checkout", "routes/checkout.tsx", { id: "checkout-en" }),
  route("en/order/confirmation", "routes/confirmation.tsx", { id: "confirmation-en" }),
  route("en/my-account", "routes/account.tsx", { id: "account-en" }),
  route("api/pro-applications", "routes/api.pro-applications.ts"),
  route("api/shipping/pickup-points", "routes/api.pickup-points.ts"),
  route("api/shipping/quote", "routes/api.shipping-quote.ts"),
  route("api/checkout/payment-intent", "routes/api.checkout.ts"),
  route("api/orders/:id", "routes/api.order.ts"),
  route("api/orders/:id/invoice", "routes/api.invoice.ts"),
  route("api/webhooks/stripe", "routes/api.webhook-stripe.ts"),
  route("api/webhooks/shippo", "routes/api.webhook-shippo.ts"),
  route("api/webhooks/sendcloud", "routes/api.webhook-sendcloud.ts"),
  route("api/admin/pro-applications/:id/decision", "routes/api.admin-pro-decision.ts"),
  route("api/admin/orders/:id/label", "routes/api.admin-order-label.ts"),
  route("api/admin/shipments/:id/label", "routes/api.admin-sendcloud-label.ts"),
  route("api/admin/orders/:orderId/shipments/:shipmentId/refund-label", "routes/api.admin-shipment-label-refund.ts"),
  route("api/admin/orders/:id/refund", "routes/api.admin-order-refund.ts"),
  route("api/cron/commerce", "routes/api.cron-commerce.ts"),
  route("media/:asset", "routes/media.ts"),
  route("sitemap.xml", "routes/sitemap.ts"),
  route("robots.txt", "routes/robots.ts"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
