import type { ActionFunctionArgs, LoaderFunctionArgs, MetaFunction } from "react-router";
import { Form, Link, redirect, useActionData, useLoaderData } from "react-router";
import { z } from "zod";
import { formatMoney } from "~/domain/money";
import { getViewer } from "~/lib/auth.server";
import { getLocale } from "~/lib/i18n";
import { pageMeta } from "~/lib/seo";
import { createRequestSupabase, createServiceSupabase } from "~/lib/supabase.server";

const addressSchema = z.object({ label: z.string().trim().max(80).default(""), company: z.string().trim().max(120).default(""), firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), line1: z.string().trim().min(3).max(160), line2: z.string().trim().max(160).default(""), postalCode: z.string().trim().min(2).max(20), city: z.string().trim().min(1).max(100), countryCode: z.string().trim().regex(/^[A-Z]{2}$/), phone: z.string().trim().max(30).default("") });

export async function loader({ request }: LoaderFunctionArgs) {
  const locale = getLocale(request); const viewer = await getViewer(request); const url = new URL(request.url); const setPassword = url.searchParams.get("set-password") === "1"; const authError = url.searchParams.get("auth_error");
  if (!viewer) return { locale, viewer: null, orders: [], addresses: [], setPassword, authError };
  const client = createServiceSupabase();
  const [{ data: orders }, { data: addresses }] = client ? await Promise.all([client.from("orders").select("id,order_number,status,total_cents,created_at,paid_at,shipments(carrier,tracking_number,tracking_url,status)").eq("profile_id", viewer.user.id).order("created_at", { ascending: false }).limit(50), client.from("addresses").select("*").eq("profile_id", viewer.user.id).order("created_at")]) : [{ data: [] }, { data: [] }];
  return { locale, viewer: { user: { id: viewer.user.id, email: viewer.user.email }, profile: viewer.profile }, orders: orders ?? [], addresses: addresses ?? [], setPassword, authError };
}

export async function action({ request }: ActionFunctionArgs) {
  const locale = getLocale(request); const accountPath = locale === "en-GB" ? "/en/my-account" : "/mon-compte"; const form = await request.formData(); const intent = String(form.get("intent") ?? "login");
  const supabase = createRequestSupabase(request);
  if (!supabase) return { ok: false, message: locale === "en-GB" ? "Authentication is not configured in this environment." : "L’authentification n’est pas configurée dans cet environnement." };
  if (intent === "update_password") { const parsed = z.string().min(10).max(200).safeParse(form.get("password")); if (!parsed.success) return { ok: false, message: locale === "en-GB" ? "Use at least 10 characters." : "Utilisez au moins 10 caractères." }; const { error } = await supabase.client.auth.updateUser({ password: parsed.data }); if (error) return { ok: false, message: error.message }; return redirect(accountPath, { headers: supabase.responseHeaders }); }
  if (intent === "save_address" || intent === "delete_address") {
    const { data: { user } } = await supabase.client.auth.getUser(); if (!user) return { ok: false, message: "Authentication required." };
    if (intent === "delete_address") { const id = z.uuid().safeParse(form.get("addressId")); if (!id.success) return { ok: false, message: "Invalid address." }; const { error } = await supabase.client.from("addresses").delete().eq("id", id.data).eq("profile_id", user.id); return { ok: !error, message: error?.message ?? (locale === "en-GB" ? "Address deleted." : "Adresse supprimée.") }; }
    const parsed = addressSchema.safeParse(Object.fromEntries(form)); if (!parsed.success) return { ok: false, message: locale === "en-GB" ? "Please complete the address." : "Veuillez compléter l’adresse." };
    const { error } = await supabase.client.from("addresses").insert({ profile_id: user.id, label: parsed.data.label, company: parsed.data.company, first_name: parsed.data.firstName, last_name: parsed.data.lastName, line1: parsed.data.line1, line2: parsed.data.line2, postal_code: parsed.data.postalCode, city: parsed.data.city, country_code: parsed.data.countryCode, phone: parsed.data.phone }); return { ok: !error, message: error?.message ?? (locale === "en-GB" ? "Address saved." : "Adresse enregistrée.") };
  }
  if (intent === "logout") { await supabase.client.auth.signOut(); return redirect(accountPath, { headers: supabase.responseHeaders }); }
  const email = String(form.get("email") ?? ""); const password = String(form.get("password") ?? "");
  if (intent === "register" && password.length < 10) return { ok: false, message: locale === "en-GB" ? "Use at least 10 characters to create an account." : "Utilisez au moins 10 caractères pour créer un compte." };
  if (intent === "reset") { const confirm = `${new URL(request.url).origin}/auth/confirm?next=${encodeURIComponent(`${accountPath}?set-password=1`)}`; const { error } = await supabase.client.auth.resetPasswordForEmail(email, { redirectTo: confirm }); return { ok: !error, message: error?.message ?? (locale === "en-GB" ? "Reset email sent." : "E-mail de réinitialisation envoyé.") }; }
  const result = intent === "register" ? await supabase.client.auth.signUp({ email, password, options: { emailRedirectTo: `${new URL(request.url).origin}/auth/confirm?next=${encodeURIComponent(accountPath)}` } }) : await supabase.client.auth.signInWithPassword({ email, password });
  if (result.error) return { ok: false, message: result.error.message };
  return redirect(accountPath, { headers: supabase.responseHeaders });
}

export const meta: MetaFunction<typeof loader> = ({ data }) => pageMeta(data?.locale === "en-GB" ? "My account | Zen Coffee Lab" : "Mon compte | Zen Coffee Lab", data?.locale === "en-GB" ? "Orders, invoices, tracking and addresses." : "Commandes, factures, suivis et adresses.", data?.locale === "en-GB" ? "/en/my-account" : "/mon-compte");

export default function Account() {
  const { locale, viewer, orders, addresses, setPassword, authError } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); const english = locale === "en-GB";
  if (viewer) return <>
    <header className="page-hero"><p className="eyebrow">{english ? "Private space" : "Espace privé"}</p><h1>{english ? "Welcome back" : "Bienvenue"}</h1><p className="lede">{viewer.user.email}</p></header>
    {setPassword ? <Form method="post" className="form-card"><input type="hidden" name="intent" value="update_password" /><h2>{english ? "Choose your password" : "Choisissez votre mot de passe"}</h2>{result?.message ? <p className="form-message form-error">{result.message}</p> : null}<div className="field"><label>{english ? "New password" : "Nouveau mot de passe"}<input name="password" type="password" minLength={10} required autoComplete="new-password" /></label></div><button className="button button--dark" type="submit">{english ? "Save password" : "Enregistrer le mot de passe"}</button></Form> : null}
    <section className="page-shell section">
      <div className="section-header"><div><p className="eyebrow">{english ? "History" : "Historique"}</p><h2>{english ? "Your orders" : "Vos commandes"}</h2></div>{viewer.profile?.professional_status === "approved" ? <Link className="button button--dark" to={english ? "/en/professional" : "/professionnel"}>{english ? "Professional shop" : "Boutique pro"}</Link> : null}</div>
      {orders.length ? <div className="ui-card"><table className="ui-table"><thead><tr><th>{english ? "Order" : "Commande"}</th><th>{english ? "Date" : "Date"}</th><th>{english ? "Status" : "Statut"}</th><th>Total</th><th>{english ? "Documents" : "Documents"}</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.order_number}</strong></td><td>{new Date(order.created_at).toLocaleDateString(locale)}</td><td><span className="ui-badge">{order.status}</span></td><td>{formatMoney(order.total_cents, locale)}</td><td>{order.paid_at ? <a className="text-link" href={`/api/orders/${order.id}/invoice`}>{english ? "Invoice PDF" : "Facture PDF"}</a> : "—"}{order.shipments?.[0]?.tracking_url ? <><br /><a className="text-link" href={order.shipments[0].tracking_url} target="_blank" rel="noreferrer">{english ? "Track" : "Suivre"}</a></> : null}</td></tr>)}</tbody></table></div> : <div className="article-card"><h3>{english ? "No orders yet" : "Aucune commande pour le moment"}</h3><p>{english ? "Your paid orders, invoices and tracking will appear here." : "Vos commandes payées, factures et suivis apparaîtront ici."}</p></div>}
      <section style={{ marginTop: "3rem" }}><div className="section-header"><div><p className="eyebrow">{english ? "Saved details" : "Coordonnées enregistrées"}</p><h2>{english ? "Your addresses" : "Vos adresses"}</h2></div></div>{result?.message ? <p className={result.ok ? "form-message" : "form-message form-error"} role="status">{result.message}</p> : null}<div className="article-grid">{addresses.map((address) => <article className="article-card" key={address.id}><h3>{address.label || address.city}</h3><p>{address.first_name} {address.last_name}<br />{address.line1}<br />{address.postal_code} {address.city} · {address.country_code}</p><Form method="post"><input type="hidden" name="intent" value="delete_address" /><input type="hidden" name="addressId" value={address.id} /><button className="ui-button ui-button--ghost ui-button--sm" type="submit">{english ? "Delete" : "Supprimer"}</button></Form></article>)}</div><Form method="post" className="form-card"><input type="hidden" name="intent" value="save_address" /><h3>{english ? "Add an address" : "Ajouter une adresse"}</h3><div className="form-grid"><div className="field"><label>{english ? "Label" : "Libellé"}<input name="label" placeholder={english ? "Home" : "Maison"} /></label></div><div className="field"><label>{english ? "Company" : "Société"}<input name="company" /></label></div><div className="field"><label>{english ? "First name" : "Prénom"}<input name="firstName" required /></label></div><div className="field"><label>{english ? "Last name" : "Nom"}<input name="lastName" required /></label></div><div className="field field--wide"><label>{english ? "Address" : "Adresse"}<input name="line1" required /></label></div><div className="field field--wide"><label>{english ? "Address line 2" : "Complément"}<input name="line2" /></label></div><div className="field"><label>{english ? "Postcode" : "Code postal"}<input name="postalCode" required /></label></div><div className="field"><label>{english ? "City" : "Ville"}<input name="city" required /></label></div><div className="field"><label>{english ? "Country code" : "Code pays"}<input name="countryCode" defaultValue="FR" maxLength={2} required /></label></div><div className="field"><label>{english ? "Phone" : "Téléphone"}<input name="phone" type="tel" /></label></div></div><button className="button button--dark" type="submit">{english ? "Save address" : "Enregistrer l’adresse"}</button></Form></section><Form method="post" style={{ marginTop: "2rem" }}><input type="hidden" name="intent" value="logout" /><button className="button button--ghost" type="submit">{english ? "Sign out" : "Se déconnecter"}</button></Form>
    </section>
  </>;
  return <>
    <header className="page-hero"><p className="eyebrow">{english ? "Private space" : "Espace privé"}</p><h1>{english ? "Your account" : "Votre compte"}</h1><p className="lede">{english ? "Find your orders, invoices, addresses and tracking." : "Retrouvez vos commandes, factures, adresses et suivis."}</p></header>
    <Form method="post" className="form-card"><h2>{english ? "Sign in" : "Se connecter"}</h2>{authError ? <p className="form-message form-error" role="alert">{authError}</p> : null}{result?.message ? <p className={result.ok ? "form-message" : "form-message form-error"} role="status">{result.message}</p> : null}<div className="form-grid"><div className="field field--wide"><label htmlFor="account-email">Email</label><input id="account-email" name="email" type="email" required autoComplete="email" /></div><div className="field field--wide"><label htmlFor="account-password">{english ? "Password" : "Mot de passe"}</label><input id="account-password" name="password" type="password" minLength={8} required autoComplete="current-password" /></div></div><div style={{ display: "flex", gap: ".7rem", flexWrap: "wrap" }}><button className="button button--dark" name="intent" value="login" type="submit">{english ? "Sign in" : "Se connecter"}</button><button className="button button--ghost" name="intent" value="register" type="submit">{english ? "Create an account" : "Créer un compte"}</button><button className="button button--ghost" formNoValidate name="intent" value="reset" type="submit">{english ? "Reset password" : "Mot de passe oublié"}</button></div></Form>
  </>;
}
