import { Plus, Trash2 } from "lucide-react";
import { z } from "zod";
import type { ActionFunctionArgs, LoaderFunctionArgs, MetaFunction } from "react-router";
import { Form, Link, useActionData, useLoaderData, useLocation } from "react-router";
import { AdminShell } from "~/components/admin-shell";
import { RichTextEditor } from "~/components/rich-text-editor";
import { requireAdmin } from "~/lib/auth.server";
import { parseRichTextInput, storedBlocksToRichTextDocument } from "~/lib/rich-text";
import { createServiceSupabase } from "~/lib/supabase.server";

type Translation = { locale: "fr-FR" | "en-GB"; title: string; excerpt: string; blocks: Array<{ type?: string; content: unknown }>; seo_title: string; seo_description: string };
type Article = { id: string; slug: string; status: "draft" | "published" | "archived"; published_at: string; advice_translations: Translation[] };
const schema = z.object({ intent: z.literal("save_advice"), id: z.preprocess((v) => v === "" ? undefined : v, z.uuid().optional()), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), status: z.enum(["draft", "published", "archived"]), publishedAt: z.string().min(10), titleFr: z.string().trim().min(3), titleEn: z.string().trim().min(3), excerptFr: z.string().trim().min(10), excerptEn: z.string().trim().min(10), bodyFr: z.string().trim().min(20), bodyEn: z.string().trim().min(20), seoTitleFr: z.string().trim().min(3), seoTitleEn: z.string().trim().min(3), seoDescriptionFr: z.string().trim().min(10), seoDescriptionEn: z.string().trim().min(10), introImageUrlFr: z.string().trim().max(2000).optional(), introImageUrlEn: z.string().trim().max(2000).optional(), introImageAltFr: z.string().trim().max(300).optional(), introImageAltEn: z.string().trim().max(300).optional(), bodyImageUrlFr: z.string().trim().max(2000).optional(), bodyImageUrlEn: z.string().trim().max(2000).optional(), bodyImageAltFr: z.string().trim().max(300).optional(), bodyImageAltEn: z.string().trim().max(300).optional(), introImageFirstFr: z.string().optional(), introImageFirstEn: z.string().optional(), bodyImageFirstFr: z.string().optional(), bodyImageFirstEn: z.string().optional() });
const deleteSchema = z.object({ intent: z.literal("delete_advice"), id: z.uuid() });

export async function loader({ request }: LoaderFunctionArgs) { const admin = await requireAdmin(request); if (admin.demo) return { demo: true, articles: [] as Article[] }; const client = createServiceSupabase(); if (!client) throw new Response("Database unavailable.", { status: 503 }); const { data, error } = await client.from("advice_articles").select("*,advice_translations(*)").order("created_at", { ascending: false }); if (error) throw new Response(error.message, { status: 500 }); return { demo: false, articles: (data ?? []) as Article[] }; }
export async function action({ request }: ActionFunctionArgs) { const admin = await requireAdmin(request); if (admin.demo) return { ok: false, message: "Lecture seule en démonstration." }; const form = Object.fromEntries(await request.formData()); const client = createServiceSupabase(); if (!client) return { ok: false, message: "Base indisponible." }; if (form.intent === "delete_advice") { const parsed = deleteSchema.safeParse(form); if (!parsed.success) return { ok: false, message: "Article invalide." }; const { error } = await client.from("advice_articles").delete().eq("id", parsed.data.id); return error ? { ok: false, message: error.message } : { ok: true, message: "Article supprimé." }; } const parsed = schema.safeParse(form); if (!parsed.success) return { ok: false, message: "Complétez les deux langues et les deux blocs." }; const bodyFr = parseRichTextInput(parsed.data.bodyFr); const bodyEn = parseRichTextInput(parsed.data.bodyEn); if (!bodyFr || !bodyEn) return { ok: false, message: "Le texte du bloc principal est trop court." }; const values = { slug: parsed.data.slug, status: parsed.data.status, published_at: new Date(parsed.data.publishedAt).toISOString() }; const mutation = parsed.data.id ? await client.from("advice_articles").update(values).eq("id", parsed.data.id).select("id").single() : await client.from("advice_articles").insert(values).select("id").single(); if (mutation.error || !mutation.data) return { ok: false, message: mutation.error?.message ?? "Article non enregistré." }; const translation = (locale: "fr-FR" | "en-GB", suffix: "Fr" | "En", body: typeof bodyFr) => ({ article_id: mutation.data.id, locale, title: parsed.data[`title${suffix}`], excerpt: parsed.data[`excerpt${suffix}`], seo_title: parsed.data[`seoTitle${suffix}`], seo_description: parsed.data[`seoDescription${suffix}`], blocks: [{ type: "richText", content: body }, { type: "storyLayout", content: { introImageUrl: parsed.data[`introImageUrl${suffix}`] ?? "", introImageAlt: parsed.data[`introImageAlt${suffix}`] ?? "", introImageFirst: parsed.data[`introImageFirst${suffix}`] === "true", bodyImageUrl: parsed.data[`bodyImageUrl${suffix}`] ?? "", bodyImageAlt: parsed.data[`bodyImageAlt${suffix}`] ?? "", bodyImageFirst: parsed.data[`bodyImageFirst${suffix}`] === "true" } }] }); const { error } = await client.from("advice_translations").upsert([translation("fr-FR", "Fr", bodyFr), translation("en-GB", "En", bodyEn)], { onConflict: "article_id,locale" }); return error ? { ok: false, message: error.message } : { ok: true, message: "Article enregistré." }; }
export const meta: MetaFunction = () => [{ title: "Conseils | Administration Zen Coffee Lab" }];

function layout(translation?: Translation) { return translation?.blocks.find((block) => block.type === "storyLayout")?.content as Record<string, unknown> | undefined; }
function BlockFields({ locale, translation, demo }: { locale: "Fr" | "En"; translation?: Translation; demo: boolean }) { const english = locale === "En"; const data = layout(translation); return <fieldset className="admin-story-editor"><legend>{english ? "Article layout" : "Mise en page de l’article"}</legend><section className="admin-story-editor__block"><h3>{english ? "Block 1 · Introduction" : "Bloc 1 · Introduction"}</h3><label>{english ? "Text" : "Texte"}<textarea name={`excerpt${locale}`} defaultValue={translation?.excerpt ?? ""} required /></label><label>{english ? "Image URL" : "URL de l’image"}<input name={`introImageUrl${locale}`} type="url" defaultValue={String(data?.introImageUrl ?? "")} /></label><label>{english ? "Alt text" : "Texte alternatif"}<input name={`introImageAlt${locale}`} defaultValue={String(data?.introImageAlt ?? "")} /></label></section><section className="admin-story-editor__block"><h3>{english ? "Block 2 · Text left / image right" : "Bloc 2 · Texte à gauche / image à droite"}</h3><RichTextEditor name={`body${locale}`} label={english ? "Text" : "Texte"} initialContent={storedBlocksToRichTextDocument(translation?.blocks)} disabled={demo} /><label>{english ? "Image URL" : "URL de l’image"}<input name={`bodyImageUrl${locale}`} type="url" defaultValue={String(data?.bodyImageUrl ?? "")} /></label><label>{english ? "Alt text" : "Texte alternatif"}<input name={`bodyImageAlt${locale}`} defaultValue={String(data?.bodyImageAlt ?? "")} /></label></section><section className="admin-story-editor__block"><h3>{english ? "Block 3 · Image left / text right" : "Bloc 3 · Image à gauche / texte à droite"}</h3><label>{english ? "Text" : "Texte"}<textarea name={`body3${locale}`} defaultValue={String(data?.body3 ?? "")} /></label><label>{english ? "Image URL" : "URL de l’image"}<input name={`body3ImageUrl${locale}`} type="url" defaultValue={String(data?.body3ImageUrl ?? "")} /></label><label>{english ? "Alt text" : "Texte alternatif"}<input name={`body3ImageAlt${locale}`} defaultValue={String(data?.body3ImageAlt ?? "")} /></label></section></fieldset>; }
function ArticleForm({ article, demo }: { article?: Article; demo: boolean }) { const fr = article?.advice_translations.find((item) => item.locale === "fr-FR"); const en = article?.advice_translations.find((item) => item.locale === "en-GB"); return <Form method="post"><input type="hidden" name="intent" value="save_advice" /><input type="hidden" name="id" value={article?.id ?? ""} /><div className="form-grid"><label>Slug<input name="slug" defaultValue={article?.slug ?? ""} required /></label><label>Statut<select name="status" defaultValue={article?.status ?? "draft"}><option value="draft">Brouillon</option><option value="published">Publié</option><option value="archived">Archivé</option></select></label><label>Date de publication<input name="publishedAt" type="datetime-local" defaultValue={(article?.published_at ?? new Date().toISOString()).slice(0, 16)} required /></label></div><div className="admin-content-columns"><fieldset><legend>Français</legend><label>Titre<input name="titleFr" defaultValue={fr?.title ?? ""} required /></label><BlockFields locale="Fr" translation={fr} demo={demo} /><label>Titre SEO<input name="seoTitleFr" defaultValue={fr?.seo_title ?? ""} required /></label><label>Description SEO<textarea name="seoDescriptionFr" defaultValue={fr?.seo_description ?? ""} required /></label></fieldset><fieldset><legend>English</legend><label>Title<input name="titleEn" defaultValue={en?.title ?? ""} required /></label><BlockFields locale="En" translation={en} demo={demo} /><label>SEO title<input name="seoTitleEn" defaultValue={en?.seo_title ?? ""} required /></label><label>SEO description<textarea name="seoDescriptionEn" defaultValue={en?.seo_description ?? ""} required /></label></fieldset></div><div className="admin-editor__actions"><button className="ui-button ui-button--default" disabled={demo}>{article ? "Enregistrer" : <><Plus /> Nouveau blog</>}</button>{article ? <Link className="ui-button ui-button--ghost" to={`/conseils/${article.slug}`}>Lire l’article</Link> : null}</div></Form>; }
export default function AdminAdvice() { const { demo, articles } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); const query = new URLSearchParams(useLocation().search); const creating = query.get("new") === "1"; const selected = query.get("article"); return <AdminShell active="advice"><header className="admin-heading"><div><p className="eyebrow">Mini-CMS</p><h1>Conseils</h1><p className="admin-heading__description">Éditez les deux blocs de texte et d’image de chaque publication.</p></div>{creating ? null : <Link className="ui-button ui-button--default" to="/admin/conseils?new=1"><Plus /> Nouveau blog</Link>}</header>{result?.message ? <p className={result.ok ? "form-message" : "form-message form-error"}>{result.message}</p> : null}<div className="admin-content-list">{articles.map((article) => { const title = article.advice_translations.find((item) => item.locale === "fr-FR")?.title ?? article.slug; return <details className="ui-card admin-content-page" key={article.id} open={selected === article.id}><summary><strong>{title}</strong><span className="ui-badge">{article.status}</span></summary><ArticleForm article={article} demo={demo} /><Form method="post" className="admin-delete-form"><input type="hidden" name="intent" value="delete_advice" /><input type="hidden" name="id" value={article.id} /><button className="ui-button ui-button--danger ui-button--sm" disabled={demo}><Trash2 /> Supprimer</button></Form></details>; })}</div>{creating ? <section className="ui-card admin-editor"><h2>Nouveau blog</h2><ArticleForm demo={demo} /></section> : null}</AdminShell>; }
