import { BookOpen, CircleHelp, Plus } from "lucide-react";
import { z } from "zod";
import type { ActionFunctionArgs, LoaderFunctionArgs, MetaFunction } from "react-router";
import { Form, Link, useActionData, useLoaderData } from "react-router";
import { Logo } from "~/components/logo";
import { requireAdmin } from "~/lib/auth.server";
import { createServiceSupabase } from "~/lib/supabase.server";

const faqSchema = z.object({ intent: z.literal("save_faq"), id: z.preprocess((value) => value === "" ? undefined : value, z.uuid().optional()), position: z.coerce.number().int().nonnegative(), active: z.string().optional().transform(Boolean), questionFr: z.string().trim().min(5), answerFr: z.string().trim().min(10), questionEn: z.string().trim().min(5), answerEn: z.string().trim().min(10) });
const adviceSchema = z.object({ intent: z.literal("save_advice"), id: z.preprocess((value) => value === "" ? undefined : value, z.uuid().optional()), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), status: z.enum(["draft", "published", "archived"]), publishedAt: z.string().min(10), titleFr: z.string().trim().min(3), titleEn: z.string().trim().min(3), excerptFr: z.string().trim().min(10), excerptEn: z.string().trim().min(10), bodyFr: z.string().trim().min(20), bodyEn: z.string().trim().min(20), seoTitleFr: z.string().trim().min(3), seoTitleEn: z.string().trim().min(3), seoDescriptionFr: z.string().trim().min(10), seoDescriptionEn: z.string().trim().min(10) });

export async function loader({ request }: LoaderFunctionArgs) {
  const admin = await requireAdmin(request); if (admin.demo) return { demo: true, faq: [], articles: [] };
  const client = createServiceSupabase(); if (!client) throw new Response("Database unavailable.", { status: 503 });
  const [{ data: faq, error: faqError }, { data: articles, error: adviceError }] = await Promise.all([client.from("faq_items").select("*").order("position"), client.from("advice_articles").select("*,advice_translations(*)").order("created_at", { ascending: false })]);
  if (faqError || adviceError) throw new Response(faqError?.message ?? adviceError?.message, { status: 500 }); return { demo: false, faq: faq ?? [], articles: articles ?? [] };
}

export async function action({ request }: ActionFunctionArgs) {
  const admin = await requireAdmin(request); if (admin.demo) return { ok: false, message: "Lecture seule en démonstration." }; const form = Object.fromEntries(await request.formData()); const client = createServiceSupabase(); if (!client) return { ok: false, message: "Base indisponible." };
  if (form.intent === "save_faq") {
    const parsed = faqSchema.safeParse(form); if (!parsed.success) return { ok: false, message: "Les quatre textes de FAQ sont requis." }; const values = { position: parsed.data.position, active: parsed.data.active, question_fr: parsed.data.questionFr, answer_fr: parsed.data.answerFr, question_en: parsed.data.questionEn, answer_en: parsed.data.answerEn };
    const mutation = parsed.data.id ? await client.from("faq_items").update(values).eq("id", parsed.data.id).select("id").single() : await client.from("faq_items").insert(values).select("id").single(); if (mutation.error || !mutation.data) return { ok: false, message: mutation.error?.message ?? "FAQ non enregistrée." };
    await client.from("audit_log").insert({ actor_id: admin.id, action: parsed.data.id ? "faq.updated" : "faq.created", entity_type: "faq_item", entity_id: mutation.data.id, after_data: parsed.data }); return { ok: true, message: "FAQ enregistrée." };
  }
  const parsed = adviceSchema.safeParse(form); if (!parsed.success) return { ok: false, message: "Les versions française et anglaise du conseil sont requises." };
  const articleValues = { slug: parsed.data.slug, status: parsed.data.status, published_at: new Date(parsed.data.publishedAt).toISOString() }; const mutation = parsed.data.id ? await client.from("advice_articles").update(articleValues).eq("id", parsed.data.id).select("id").single() : await client.from("advice_articles").insert(articleValues).select("id").single(); if (mutation.error || !mutation.data) return { ok: false, message: mutation.error?.message ?? "Conseil non enregistré." };
  const blocks = (text: string) => text.split(/\n{2,}/).map((content) => content.trim()).filter(Boolean).map((content) => ({ type: "paragraph", content })); const translations = [{ locale: "fr-FR", title: parsed.data.titleFr, excerpt: parsed.data.excerptFr, blocks: blocks(parsed.data.bodyFr), seo_title: parsed.data.seoTitleFr, seo_description: parsed.data.seoDescriptionFr }, { locale: "en-GB", title: parsed.data.titleEn, excerpt: parsed.data.excerptEn, blocks: blocks(parsed.data.bodyEn), seo_title: parsed.data.seoTitleEn, seo_description: parsed.data.seoDescriptionEn }].map((translation) => ({ ...translation, article_id: mutation.data.id }));
  const { error } = await client.from("advice_translations").upsert(translations, { onConflict: "article_id,locale" }); if (error) { if (!parsed.data.id) await client.from("advice_articles").delete().eq("id", mutation.data.id); return { ok: false, message: error.message }; }
  await client.from("audit_log").insert({ actor_id: admin.id, action: parsed.data.id ? "advice.updated" : "advice.created", entity_type: "advice_article", entity_id: mutation.data.id, after_data: parsed.data }); return { ok: true, message: "Conseil enregistré." };
}

export const meta: MetaFunction = () => [{ title: "FAQ & Conseils | Zen Coffee Lab" }, { name: "robots", content: "noindex,nofollow" }];

function FaqForm({ item, demo }: { item?: any; demo: boolean }) { return <Form method="post" className="form-grid"><input type="hidden" name="intent" value="save_faq" /><input type="hidden" name="id" value={item?.id ?? ""} /><div className="field"><label>Position<input name="position" type="number" min="0" defaultValue={item?.position ?? 0} /></label></div><label><input name="active" type="checkbox" defaultChecked={item?.active ?? true} /> Visible</label><div className="field field--wide"><label>Question FR<input name="questionFr" defaultValue={item?.question_fr ?? ""} required /></label></div><div className="field field--wide"><label>Réponse FR<textarea name="answerFr" defaultValue={item?.answer_fr ?? ""} required /></label></div><div className="field field--wide"><label>Question EN<input name="questionEn" defaultValue={item?.question_en ?? ""} required /></label></div><div className="field field--wide"><label>Réponse EN<textarea name="answerEn" defaultValue={item?.answer_en ?? ""} required /></label></div><button className="ui-button ui-button--default" type="submit" disabled={demo}>{item ? "Enregistrer" : <><Plus aria-hidden="true" /> Ajouter</>}</button></Form>; }

function AdviceForm({ article, demo }: { article?: any; demo: boolean }) { const fr = article?.advice_translations?.find((item: any) => item.locale === "fr-FR"); const en = article?.advice_translations?.find((item: any) => item.locale === "en-GB"); const body = (translation: any) => (translation?.blocks ?? []).map((block: any) => block.content).join("\n\n"); return <Form method="post"><input type="hidden" name="intent" value="save_advice" /><input type="hidden" name="id" value={article?.id ?? ""} /><div className="form-grid"><div className="field"><label>Slug<input name="slug" defaultValue={article?.slug ?? ""} required /></label></div><div className="field"><label>Statut<select name="status" defaultValue={article?.status ?? "draft"}><option value="draft">Brouillon</option><option value="published">Publié</option><option value="archived">Archivé</option></select></label></div><div className="field"><label>Date de publication<input name="publishedAt" type="datetime-local" defaultValue={(article?.published_at ?? new Date().toISOString()).slice(0, 16)} required /></label></div></div><div className="admin-content-columns"><fieldset><legend>Français</legend><div className="field"><label>Titre<input name="titleFr" defaultValue={fr?.title ?? ""} required /></label></div><div className="field"><label>Extrait<textarea name="excerptFr" defaultValue={fr?.excerpt ?? ""} required /></label></div><div className="field"><label>Paragraphes<textarea name="bodyFr" defaultValue={body(fr)} required /></label></div><div className="field"><label>Titre SEO<input name="seoTitleFr" defaultValue={fr?.seo_title ?? ""} required /></label></div><div className="field"><label>Description SEO<textarea name="seoDescriptionFr" defaultValue={fr?.seo_description ?? ""} required /></label></div></fieldset><fieldset><legend>English</legend><div className="field"><label>Title<input name="titleEn" defaultValue={en?.title ?? ""} required /></label></div><div className="field"><label>Excerpt<textarea name="excerptEn" defaultValue={en?.excerpt ?? ""} required /></label></div><div className="field"><label>Paragraphs<textarea name="bodyEn" defaultValue={body(en)} required /></label></div><div className="field"><label>SEO title<input name="seoTitleEn" defaultValue={en?.seo_title ?? ""} required /></label></div><div className="field"><label>SEO description<textarea name="seoDescriptionEn" defaultValue={en?.seo_description ?? ""} required /></label></div></fieldset></div><button className="ui-button ui-button--default" type="submit" disabled={demo}>{article ? "Enregistrer" : <><Plus aria-hidden="true" /> Ajouter</>}</button></Form>; }

export default function AdminEditorial() { const { demo, faq, articles } = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); return <div className="admin-shell"><aside className="admin-sidebar"><Logo /><nav><Link to="/admin">Tableau de bord</Link><Link to="/admin/contenus">Pages</Link><Link aria-current="page" to="/admin/editorial">FAQ & Conseils</Link></nav></aside><main className="admin-main"><header className="admin-heading"><div><p className="eyebrow">Mini-CMS</p><h1>FAQ & Conseils</h1></div></header>{demo ? <p className="admin-notice">Connectez Supabase pour modifier ces contenus.</p> : null}{result?.message ? <p className={result.ok ? "form-message" : "form-message form-error"}>{result.message}</p> : null}<section><div className="section-header"><div><CircleHelp aria-hidden="true" /><h2>FAQ</h2></div></div><div className="admin-content-list">{faq.map((item) => <details className="ui-card admin-content-page" key={item.id}><summary><strong>{item.question_fr}</strong><span className="ui-badge">{item.active ? "visible" : "masquée"}</span></summary><FaqForm item={item} demo={demo} /></details>)}</div><div className="ui-card admin-editor"><h3>Nouvelle question</h3><FaqForm demo={demo} /></div></section><section style={{ marginTop: "3rem" }}><div className="section-header"><div><BookOpen aria-hidden="true" /><h2>Conseils</h2></div></div><div className="admin-content-list">{articles.map((article) => <details className="ui-card admin-content-page" key={article.id}><summary><strong>{article.slug}</strong><span className="ui-badge">{article.status}</span></summary><AdviceForm article={article} demo={demo} /></details>)}</div><div className="ui-card admin-editor"><h3>Nouveau conseil</h3><AdviceForm demo={demo} /></div></section></main></div>; }
